import type { Doctor } from "@/types/doctor";

export const mockDoctors: Doctor[] = [
  {
    id: "doc-1",
    name: "Dr. Anika Rao",
    specialty: "General Medicine",
    imageUrl: null,
    experienceYears: 12,
    qualification: "MBBS, MD (General Medicine)",
    bio: "Dr. Anika Rao is an experienced general physician dedicated to providing comprehensive primary care for patients of all ages, focusing on preventive health and wellness.",
    rating: 4.8,
    reviewCount: 142,
    consultationFee: 80,
    availableNextDays: 0,
  },
  {
    id: "doc-2",
    name: "Dr. Rohan Sharma",
    specialty: "Dermatology",
    imageUrl: null,
    experienceYears: 8,
    qualification: "MBBS, DDVL",
    bio: "Specializing in clinical and cosmetic dermatology, Dr. Rohan Sharma offers expert treatments for acne, eczema, and advanced skin rejuvenation therapies.",
    rating: 4.9,
    reviewCount: 96,
    consultationFee: 120,
    availableNextDays: 2,
  },
  {
    id: "doc-3",
    name: "Dr. Priya Patel",
    specialty: "Cardiology",
    imageUrl: null,
    experienceYears: 15,
    qualification: "MBBS, MD, DM (Cardiology)",
    bio: "Dr. Priya Patel is a senior interventional cardiologist with over 15 years of experience in managing complex heart conditions and promoting cardiovascular health.",
    rating: 4.7,
    reviewCount: 231,
    consultationFee: 150,
    availableNextDays: 1,
  },
  {
    id: "doc-4",
    name: "Dr. Vikram Singh",
    specialty: "Pediatrics",
    imageUrl: null,
    experienceYears: 10,
    qualification: "MBBS, MD (Pediatrics)",
    bio: "Dr. Vikram Singh provides compassionate care for infants, children, and adolescents, ensuring their healthy growth and development through comprehensive pediatric services.",
    rating: 4.6,
    reviewCount: 88,
    consultationFee: 90,
    availableNextDays: 0,
  },
  {
    id: "doc-5",
    name: "Dr. Meera Iyer",
    specialty: "Neurology",
    imageUrl: null,
    experienceYears: 18,
    qualification: "MBBS, MD, DM (Neurology)",
    bio: "With nearly two decades of experience, Dr. Meera Iyer specializes in diagnosing and treating complex neurological disorders, including migraines, epilepsy, and stroke.",
    rating: 4.9,
    reviewCount: 310,
    consultationFee: 200,
    availableNextDays: 3,
  },
  {
    id: "doc-6",
    name: "Dr. Sanjay Gupta",
    specialty: "Orthopedics",
    imageUrl: null,
    experienceYears: 14,
    qualification: "MBBS, MS (Orthopedics)",
    bio: "Dr. Sanjay Gupta is a renowned orthopedic surgeon focusing on joint replacements, sports injuries, and advanced minimally invasive fracture treatments.",
    rating: 4.7,
    reviewCount: 155,
    consultationFee: 130,
    availableNextDays: 0,
  },
  {
    id: "doc-7",
    name: "Dr. Aisha Khan",
    specialty: "Gynecology",
    imageUrl: null,
    experienceYears: 9,
    qualification: "MBBS, MS (OBG)",
    bio: "Dr. Aisha Khan provides expert obstetric and gynecological care, supporting women through all stages of life with a focus on maternal health and wellness.",
    rating: 4.8,
    reviewCount: 205,
    consultationFee: 110,
    availableNextDays: 1,
  },
  {
    id: "doc-8",
    name: "Dr. Rajesh Kumar",
    specialty: "ENT Specialist",
    imageUrl: null,
    experienceYears: 11,
    qualification: "MBBS, MS (ENT)",
    bio: "Dr. Rajesh Kumar is a specialist in Otolaryngology, providing advanced medical and surgical treatments for ear, nose, and throat disorders.",
    rating: 4.5,
    reviewCount: 74,
    consultationFee: 100,
    availableNextDays: 0,
  },
  {
    id: "doc-9",
    name: "Dr. Sneha Reddy",
    specialty: "Ophthalmology",
    imageUrl: null,
    experienceYears: 7,
    qualification: "MBBS, DO",
    bio: "Dr. Sneha Reddy focuses on comprehensive eye care, including cataract diagnosis, vision correction, and management of chronic ocular conditions.",
    rating: 4.6,
    reviewCount: 112,
    consultationFee: 95,
    availableNextDays: 2,
  },
  {
    id: "doc-10",
    name: "Dr. Amit Desai",
    specialty: "Psychiatry",
    imageUrl: null,
    experienceYears: 16,
    qualification: "MBBS, MD (Psychiatry)",
    bio: "Dr. Amit Desai is a dedicated psychiatrist offering holistic mental health care, specializing in anxiety, depression, and cognitive behavioral therapies.",
    rating: 4.9,
    reviewCount: 280,
    consultationFee: 160,
    availableNextDays: 1,
  },
  {
    id: "doc-11",
    name: "Dr. Kavita Menon",
    specialty: "Dentistry",
    imageUrl: null,
    experienceYears: 6,
    qualification: "BDS, MDS",
    bio: "Dr. Kavita Menon is a highly skilled dental surgeon providing painless root canals, cosmetic dentistry, and comprehensive oral hygiene care.",
    rating: 4.7,
    reviewCount: 89,
    consultationFee: 60,
    availableNextDays: 0,
  },
  {
    id: "doc-12",
    name: "Dr. Arjun Nair",
    specialty: "Gastroenterology",
    imageUrl: null,
    experienceYears: 13,
    qualification: "MBBS, MD, DM (Gastroenterology)",
    bio: "Dr. Arjun Nair brings over a decade of expertise in treating digestive system disorders, liver diseases, and performing advanced endoscopic procedures.",
    rating: 4.8,
    reviewCount: 198,
    consultationFee: 140,
    availableNextDays: 1,
  }
];
